### ISSUE TITLE
Feature 1: User can view waitlist

### ISSUE THREAD

**Issue by chase-simmonds** [chase-simmonds/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the wait list to see who is actively waiting in line. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to see who is in line and which barber they are waiting for. The list will be in ascending order (i.e. newest additions will be at the top, while those who have been waiting longer will be at the bottom).

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="292" alt="Screen Shot 2022-07-25 at 1 14 49 PM" src="https://user-images.githubusercontent.com/65789518/180866345-702e0064-149d-432e-be2c-1b9cc1fa0960.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.
- [x] React
- [x] Database
- [x] Server
- [x] Client
- [x] Clean Up

### 🐘 Database Tasks

- [x] Update `schema.sql` to create a table that contains postId, barberId, name, phoneNumber, barberName, and createdAt
- [x] Update `data.sql` to allow post insertions

### ☁️ Server Tasks

- [x] Update `server/index.js` to populate waiting list with GET method
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component for page container
- [x] Create a component for list elements
- [x] Create component to add new wait list entry

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
