### ISSUE TITLE
Feature 2: User can create wait list entry

### ISSUE THREAD

**Issue by chase-simmonds** [chase-simmonds/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create an entry that that adds them to the wait list.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be prompted with a form to enter their name, phone number, the barber's name or 'any' if they would like the first available. Upon submitting, they will be added to the waitlist where they can see where they are in the line.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-07-25 at 4 27 18 PM](https://user-images.githubusercontent.com/65789518/180891460-acad4ae7-9e01-4aaa-a35b-f970e00e5d06.png)
![Screen Shot 2022-07-25 at 4 27 26 PM](https://user-images.githubusercontent.com/65789518/180891459-ccfc39ff-4280-4fe8-a7e0-4a8933c8820c.png)
![Screen Shot 2022-07-25 at 4 27 34 PM](https://user-images.githubusercontent.com/65789518/180891457-1dc6a10b-4253-41c7-bd0d-c17babdf5c98.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to store postId, name, phone number, barber name, and created at. Ensure the fields are not null. Primary key is postId. 
- [x] Update `data.sql` to insert the above into the posts table.

### ☁️ Server Tasks

- [x] Update `server/index.js` to accept data from the user using POST method. 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to render a form where users can input their name, phone number, and the barber they're visiting.
- [x] Ensure the data gets from the form, through the server, into the database.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
